### ISSUE TITLE
Error on loading vector slice with geometry

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#1162]
Hey Glenn,
If you run this case,
[geom_channel.fds](https://github.com/firemodels/fds/blob/master/Verification/Complex_Geometry/geom_channel.fds)
with the latest code and try to load a vector slice of 'U-VELOCITY (geometry)' as shown here:
<img width="1440" alt="Screen Shot 2021-07-07 at 2 38 03 PM" src="https://user-images.githubusercontent.com/4418497/124811934-04b08180-df31-11eb-9ba2-cabc332eeaf1.png">
then I get the following error:
<img width="1072" alt="Screen Shot 2021-07-07 at 2 35 01 PM" src="https://user-images.githubusercontent.com/4418497/124811969-109c4380-df31-11eb-93e2-3ace224494b4.png">

Thanks

**Comment by rmcdermo** [comment]
@marcosvanella Please look at this as well.  It's possible that FDS should not be writing anything to the SMV menu or something like that.  Thanks

**Comment by mcgratta** [comment]
Glenn -- is this related to the .ter file issue?

**Comment by marcosvanella** [comment]
We shouldn't have vector slices of (geometry) type. Not clear why we have H, Divergence or Tracer Mass Fraction in there. I made the number of cells in Y 8 and see the same, so it doesn't seem to be a 2D only issue.

**Comment by gforney** [comment]
not related to .ter file issue.  

am taking a look

**Comment by rmcdermo** [comment]
@marcosvanella Why can't we have vector slices of `SLICETYPE='GEOM'`?  (btw, is this the right notation in the input file? because we nixed the complex geometry documentation, I don't know if this is documented; maybe we should put this back?)

What output should I use to see the CUTFACE velocity component in a slice file?

**Comment by marcosvanella** [comment]
It is just not implemented. Vector slices are defined in the cartesian grid currently. The unstructured geometry slices of type (geometry) take cell scalar quantities.

**Comment by gforney** [comment]
smokeview generates vector slice menu entries for a slice quantity XXX if it sees one or more velocity components of the same slice type as slice XXX .  So you don't need VECTOR=.TRUE. in the fds input file to see vectors in smokeiew.  you  just need to output velocity slices of the same type/size/direction along with your original slice .  This doesn't answer why smokeview is not handling this case though.  I am looking.  Let me know if you don't want me to generate geometry vector slice menus and I will take i tout

**Comment by rmcdermo** [comment]
I think we need a way to view the geom slice components.  As Marcos said, we need to implement it.  For the moment, I think we need to make sure Smokeview can load whatever it provides a menu item for.

I'm just getting back to focussing on the geom stuff, so please bear with me; I'm liable to ask a lot of dumb questions.

**Comment by gforney** [comment]
any reason why the W geometry slice should have data but the U geometry slice does not ? smokeview is not handling this well (I need to add some error checks) but am wondering whether the U geom should have data

**Comment by gforney** [comment]
made a slight edit to my previous comment so check the issue tracker web page if you are reading this via email

**Comment by rmcdermo** [comment]
Not sure.  What I think should happen when we have a SLCF passing through a GEOM is that we get the "geometry" version of the slice.  If we need the Cartesian version for our own debug purposes, we can figure out how to add this.  But I think users will not want to fuss with adding extra flags and will expect to see the slice account for the geometry.

**Comment by gforney** [comment]
The midpoint of the 'X' portion of the domain is 0.5 (X goes from -0.25 to 1.25 ).  So if I understand the DB parameter correctly, I expected PBX=0.5 and DB='XMID' to generate the same slice

&SLCF PBX=0.5, QUANTITY='VELOCITY' /
&SLCF DB='XMID', QUANTITY='VELOCITY' /

But the first, PB=0.5, generates a geometry slice which is what I expected since this slice intersects with the geometry.  The second, DB='XMID', generates a cartesian slice (slice in original file format) .  smokeview has problems which I need to fix but some of the problems may be due to inconsistent slices.  

I'll get rid of all the DB slices and work on problems that still arise in smokeview

**Comment by gforney** [comment]
looks like I didn't implement vector slices for geometry slice files.  I'm doing this now.

slice file display should work for geometry slices.  let me know if you see any crashes with geometry slices for this case

**Comment by gforney** [comment]
try smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

geometry vector slices were not implemented before so I need to do some more checking.  

note, when I draw cell centered vector slice files (for structured cases) I draw both the vectors and the shaded slice contour .  since these geometry slice files  output values for each face (rather than vertices), to be consistent I'm drawing them the same way .  this is an option that can be turned off (look in Show/Hide>Slices

**Comment by rmcdermo** [comment]
I'm assuming this is fixed.  I have not seen any problem loading vector slices with geom lately.
