### ISSUE TITLE
Plot3d crashes Smokeview when loading the .q file

### ISSUE THREAD

**Issue by REI-Gardner** [firemodels/smv#1231]
When I try to open plot3d data within Smokeview the program crashes. It crashes when the terminal says it is loading the .q file.

The case that crashes is relatively large at 11.7m by  7.4m by 3.4 m. I am able to open plot3d data for smaller cases. 

I am not sure what would be helpful to upload here for this problem to be troubleshot.

**Comment by gforney** [comment]
Upload the input file ill take a look.

**Comment by REI-Gardner** [comment]
.txt version of the input file
[Army_Comparison.fds.txt](https://github.com/firemodels/smv/files/7707372/Army_Comparison.fds.txt)

**Comment by gforney** [comment]
Thanks. How much memory does your computer have.

**Comment by REI-Gardner** [comment]
16.0 GB

**Comment by gforney** [comment]
turns out it wasn't a problem with memory or the case being large.  your case was using non-default plot3d variables ie it didn't have U-VEL, V-VEL, W-VEL etc.  smokeview was having trouble with this. Try smokeview posted here

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?resourcekey=0-J_yHat7iJoBp1fk6QS8gMA&usp=sharing

**Comment by REI-Gardner** [comment]
I was able to open the plot3d data with the smv test version that shared in your last comment. Thank you for the help.

**Comment by gforney** [comment]
good.  thanks for reporting back
