### ISSUE TITLE
IOsmoke.c Foget "break"?

### ISSUE THREAD

**Issue by 823639792** [firemodels/smv#1585]
in funciton UpdateSmoke3D
```
switch(smoke3di->compression_type){
  case RLE:
       //forget break;?
  case ZLIB:
        break;
}```

**Comment by gforney** [comment]
yes.  the break was dropped on a commit I made back on October 12, 2022 .  thanks for the catch!

**Comment by gforney** [comment]
fixed in PR https://github.com/firemodels/smv/pull/1586
in case, this was affecting a smokeview you were using, a smokeview with the fix is available here: https://github.com/firemodels/test_bundles/releases/tag/SMOKEVIEW_TEST

and will show up after the next firebot pass in the nightly bundles here:
https://github.com/firemodels/test_bundles/releases/tag/FDS_TEST
