### ISSUE TITLE
smokeview won't load if missing slice files

### ISSUE THREAD

**Issue by drjfloyd** [firemodels/smv#519]
If I am running remotely on another machine, I don't always want to download all data files to check on a job.  Smokeview will not run if there are gaps in the files.  Run the attached file (makes 8 slice files) and open smokeview. It opens successfully.   Delete slice files 4-8 and smokeview will still run.  Now delete file 2 leaving just 1 and 3 (e.g. a gap). Smokeview crashes.  This is with the current release:

SMV6.6.1-2-gcee0e5d

[smvfail.txt](https://github.com/firemodels/smv/files/1670478/smvfail.txt)

**Comment by gforney** [comment]
I'll take a look

**Comment by gforney** [comment]
that bug has probably been there since the beginning!  only shows up when when you delete files in the middle.  I decrement a variable that holds the total number of slice files but was not decrementing the variable "indexing" the slice files ie in do i=1, nslicefiles , I was decrementing nslicefiles but not i.

I'm going to check to see if I made the same mistake for other file types. 

If you need to run cases before I can get a smokeview uploaded, a work around would be to edit the .smv file to remove the SLCF entries for the slice files that are not present

**Comment by gforney** [comment]
should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

I looked for the  same problem in other file types but didn't see any.   let me know if you do

**Comment by drjfloyd** [comment]
It works. Thanks.
