### ISSUE TITLE
BNDF not showing

### ISSUE THREAD

**Issue by rmcdermo** [firemodels/smv#708]
Please try the attached input file and see what happens when you try to load the boundary file.  I don't see anything.

I'm using SMV6.7.1-285-g4e12c8b_osx64.

![screen shot 2018-09-14 at 10 46 54 am](https://user-images.githubusercontent.com/4418497/45558773-b1fcfc80-b80e-11e8-86b7-51c51d36d7f6.png)

[Test_RAMP_AIT.fds.txt](https://github.com/firemodels/smv/files/2383859/Test_RAMP_AIT.fds.txt)

Suggest adding verification for all types of files: SLCF, BNDF, ISOF, etc. that can be compared to baseline images.  This can either be done numerically by creating a special case with known values for files (might be hard for some cases).  Or we could use image processing in Matlab (Python) to compare images (this would be subject to variation in numbers output by FDS, so we would have to think about how to keep this stable).

**Comment by gforney** [comment]
1. should be fixed in smokeview posted here
https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

2. I had forgotten - turns out I have implemented something close to what you suggest.  smokeview has a way of retrieving colors on the screen and making them available to itself.  I use it now to verify smoke opacity - it has actually caught errors in smoke vis a couple of times (its part of smokebot).  I'll make this more general so that it works for more than just smoke.

I envision something like creating a smokeview script command you would add to a ssf script file

COLORTEST x y r g b delta

This command would get the rgb color at pixel location (x,y).  Call the color it finds RGB .  If each component  of RGB is within delta of rgb then it passes.  Otherwise it fails.  You could put in as many COLORTEST commands for one case as you wanted. 

I've done the hard part - writing code to cause smokeview to retrieve the color it outputted to the screen.

**Comment by rmcdermo** [comment]
Thanks.  BNDF is fixed.
