### ISSUE TITLE
Smokeview crashes when comparing two boundary files

### ISSUE THREAD

**Issue by bphusted** [firemodels/smv#827]
Smokeview crashes when comparing two boundary files after the use of smokediff. I am using FDS 6.7.1 and Smokeview 6.7.6 on windows 7 (64 bit).

To reproduce the issue: 
Run the two attached files  case1.fds and case2.fds
Use smokediff -smv case1 case2

In smokeview compare any of the three boundary files and smokeview will crash. Comparing the slide files works fine.

[case1_2.zip](https://github.com/firemodels/smv/files/3293360/case1_2.zip)

**Comment by gforney** [comment]
should be fixed in smokediff posted here.  there was a problem with an uninitialized variable in a routine used by smokediff to read boundary files.  note, only the windows version has the fix.  i'll post a fix for the mac and linux version of smokediff on monday

https://drive.google.com/drive/folders/0B_wB1pJL2bFQc1F4cjJWY2duWTA?usp=sharing

**Comment by bphusted** [comment]
Super thanks, - I also tested in on my bigger case and everything works perfectly.
